version: '3.5'
services:
  my_service:
    image: webdevops/php-apache:7.4
    volumes:
      - .:/var/www/html
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html/public
    ports:
      - 8080:80
    depends_on:
      - db
  composer:
    image: composer
    volumes:
      - ./:/app
    command: composer install
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - dba:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=
      - MYSQL_ROOT_PASSWORD=
volumes:
  dba:
